---
- hosts: Centos-7-DevOps-server3.abc.com
  remote_user: test
  become: yes
  tasks:
   - name: install httpd package
     yum: name={{item}} state=installed
     with_items:
         - httpd
         - curl
         - telnet  


