---
- hosts: Centos-7-DevOps-server3.abc.com
  remote_user: test
  become: yes
  vars:
   pkg: httpd
  tasks:
   - name: install httpd package
     yum: name={{pkg}} state=installed
   - name: copy index.html
     copy: src=index.html dest=/var/www/html
   - name: start the httpd service
     service: name=httpd state=started
     ignore_errors: True


